### PR TITLE
Heavy hyperons

### PR DESCRIPTION
**Pull request by rlalik**
Several new heavy hyperons and their decay taken from PDG.
The plugin has some flags used to enable/disable Dalitz, non-Dalitz and Experimental decays but they flags are optional and can be completely transparent for users.

### CODE REVIEW

**Comment by rlalik** [comment]
#5 should be merged first

**Comment by PlutoUser** [comment]
I wonder why you changed the PIDs, in this case old ana macros will not any more. But moreover, sometimes you set the PID explicitly (70, and then starting with 75 again) and sometimes you leave it open (-1). What is the reason for this?

**Comment by rlalik** [comment]
In the old version the heavier heavy hyperons were defined first, and when i wanted to implement the decay to lighter it was making a problem because of not existing particles. So I changed the order to first define light and then gradually  higher.

I did not consider this as a problem because there was no official release with that order.
About the numbering, with 70 I wanted to start heavy hyperons, with 75 double strange hyperons, and so on. But I am fine to change it to -1. But I think that if some previous plugin will declare a new particle it may reenumerate the particles and what had some given automatic PID value with -1 may have another PID in future release. So perhaps it is safer actually to use fixed numbers for the hyperons?

Does -1 uses the next highest PID or the next after last defined?

**Comment by PlutoUser** [comment]
The -1 uses the first free place, see [here](https://github.com/PlutoUser/pluto6/blob/0fac3973da20233d65e7b379481bf6e03d46e3b2/src/PStaticData.cc#L389). I also added a list of defined particles (current version) in the docs

**Pull request merged**
