### PR TITLE
Add K*(892) definitions

### PR DESCRIPTION
**Pull request by rlalik**
This commit adds all three of K*(892) mesons and their decay channels.

### CODE REVIEW

**Comment by PlutoUser** [comment]
please be aware that there is a particle list in doc/, one should always add new particles there. I see that there is a conflict, maybe we should resort the numbers...?

**Comment by rlalik** [comment]
Well, I wasn't aware of that. I fixed pids now and updated the doc. I just picked up an arbitrary free PIDs at least some numbers away from already used PIDs.

I was also wondering whether it would actually make sense to move the strangeness particles from plugin to the core Pluto, or make strangeness always active. With current users they may be just expecting strangeness to be present out of the box.

**Comment by PlutoUser** [comment]
yes I also think that it should be enabled by default. You can do it via the Enable command in PDistributionManager.mod.cc (see dalitz_mod e.g.)

**Comment by rlalik** [comment]
It seems that it is already enabled: https://github.com/PlutoUser/pluto6/blob/371d556ae6aae71f1f5917631718715aa9727c0c/plugins/strangeness/PDistributionManager.mod.cc#L5

**Pull request merged**
